#!/bin/bash

#exit on fail
set -e

repodir="/home/ubuntu/Krowsearch/"

branch="master"
version="0"

[ -n "$1" ] && branch="$1"

cd $repodir

scripts/stopserver

git checkout $branch
git pull

scripts/startserver

screen -r search
